title: Midgard Development
# email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
url: "https://midgard-development.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  LokiMidgard

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

#source: [your repo's top level directory]
include: [".well-known"]
